server {
    listen 8008;
    location / {
        proxy_pass http://apiserver:8008;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        # sub_filter can not edit compressed bodies
        proxy_set_header Accept-Encoding "";
        proxy_read_timeout 300s;
        client_max_body_size 100m;

        sub_filter_types application/json text/plain;
        sub_filter_once off;
        sub_filter "http://192.168.0.100:8081" "http://$host:8081";
        sub_filter "http://geonosis.tailc47ef2.ts.net:8081" "http://$host:8081";
    }
}
