services:
  ppa_packages:
    build:
      context: .
      dockerfile: "${DOCKERFILE:-Dockerfile}"
    ports:
      - 80:80
    restart: always
    volumes:
      - /srv/data/hosting/volumes/ppa_packages:/var/www/html/debian
